name: test

on:
  - push
  - pull_request

jobs:
  linux-gcc-sanitize:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      - name: test
        env:
          CC: gcc
          DEBUG: -fsanitize=address,undefined -fno-sanitize-recover=all
          TESTS: regress-failed.sh regress-report-log.sh robsd-config.sh robsd-hook.sh robsd-ls.sh robsd-regress-html.sh robsd-step.sh
        run: |
          ./configure --pedantic
          make -j`nproc` test "TESTS=${TESTS}"

  linux-clang-sanitize:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      - name: test
        env:
          CC: clang
          # unsigned-integer-overflow disabled due to problem with uthash.
          DEBUG: -fsanitize=address,undefined -fno-sanitize-recover=all
          TESTS: regress-failed.sh regress-report-log.sh robsd-config.sh robsd-hook.sh robsd-ls.sh robsd-regress-html.sh robsd-step.sh
        run: |
          ./configure --pedantic
          make -j`nproc` test "TESTS=${TESTS}"

  valgrind:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install libxml2-utils valgrind
      - name: test
        env:
          CC: gcc
          EXEC: valgrind
          TESTFLAGS: -Tmemleak
          TESTS: regress-failed.sh regress-report-log.sh robsd-config.sh robsd-hook.sh robsd-ls.sh robsd-regress-html.sh robsd-step.sh
          VALGRIND_OPTS: --quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all
        run: |
          ./configure --pedantic
          make -j`nproc` test "TESTS=${TESTS}"

  ndebug:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DNDEBUG
          TESTS: regress-failed.sh regress-report-log.sh robsd-config.sh robsd-hook.sh robsd-ls.sh robsd-regress-html.sh robsd-step.sh
        run: |
          ./configure --pedantic
          make -j`nproc` test "TESTS=${TESTS}"

  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clang-tidy
        run: |
          ./configure --pedantic
          make lint-clang-tidy

  cppcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install cppcheck
      - name: cppcheck
        run: |
          ./configure --pedantic
          make lint-cppcheck
